language: node_js
node_js:
  - v7
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  fqdn: asyncjs.com
  on:
    branch: master
env:
  - GA_KEY="UA-2150808-14"
